### ISSUE TITLE
socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by placebo83** [robmarkcole/bme680-mqtt#1]
Dear Robin,

When I run your script I get the following error:

Traceback (most recent call last):
File “bme680-air-quality-RC.py”, line 24, in 
client.connect(broker)
File “/home/pi/.local/lib/python2.7/site-packages/paho/mqtt/client.py”, line 941, in connect
return self.reconnect()
File “/home/pi/.local/lib/python2.7/site-packages/paho/mqtt/client.py”, line 1075, in reconnect
sock = self._create_socket_connection()
File “/home/pi/.local/lib/python2.7/site-packages/paho/mqtt/client.py”, line 3546, in _create_socket_connection
return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
File “/usr/lib/python2.7/socket.py”, line 557, in create_connection
for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known

I searched the internet but the error mainly has something to do with no Internet/DNS problems, which shouldn’t be possible because the Pi is connected to the internet, and the MQTT server is hosted on http://192.168.1.6:8123/ 1 (My Home Assistant Pi). Do you have any idea/solution?

**Comment by robmarkcole** [comment]
For a start you should try python3

**Comment by placebo83** [comment]
Thanks for the tip, with python3 I get more or less the same error:

Traceback (most recent call last):
  File "bme680-air-quality-RC.py", line 24, in <module>
    client.connect(broker)
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1075, in reconnect
    sock = self._create_socket_connection()
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3546, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

Any idea what it could be?

**Comment by robmarkcole** [comment]
I have not run this code in a while, perhaps there was a change in a dependency that caused it - only googling would answer that. There is always a small chance that a hardware issue can cause strange errors too

**Comment by placebo83** [comment]
It wasn't a hardware issue, it was a stupid me: I put http:// in front of the ip. Deleted that and now it works. Thank you for your help!
